= The "bring AD CS to REST" API

A simple, yet powerful REST API for submitting certificates to one or more Microsoft link:https://docs.microsoft.com/en-us/windows/win32/seccrypto/certificate-services[Active Directory Certificate Services (AD CS)^] certification authorities.

== Introduction

The API allows for requesting certificates from systems that are not joined to the same Active Directory domain as the certification authorities (or not joined to any domain at all). It can serve any client operating system that is capable of submitting a REST API call. It converts certificate requests submitted via REST to the DCOM protocol. Therefor it is perfectly suited for certificate issuance scenarios from Linux, BSD, cloud services and the like.

It aims to replicate the functionality of the three main methods of the DCOM link:https://docs.microsoft.com/en-us/windows/win32/api/certcli/nn-certcli-icertrequest[ICertRequest^] Interface and make these accessible via REST. It pursiuts a low code approach, thus no fancy features. Think of it as a protocol converter (therefore the name, ADCS to REST).

=== Security

Submitted certificate requests appear on the certification authority under the security context of the Active Directory user who submitted them via the API. So permissions are handled on the CA/Template level, exactly as you would do with DCOM. You may want to combine the API with the link:https://github.com/Sleepw4lker/TameMyCerts[TameMyCerts policy module^] on your certification authorities to be able to strictly restrict requested certificate content.

I suggest using the API with link:https://docs.microsoft.com/en-us/aspnet/web-api/overview/security/basic-authentication[Basic Authentication^]. Windows Authentication (Kerberos) and Client Certificate Authentication work as well, but I advise against these because you will need Kerberos Delegation which can be a very dangerous topic that should be used with extreme caution.

As the API requires authentication, it should only be used over HTTPS.

The API also works when NTLM is disabled in the environment and thus Kerberos authentication is enforced.

== Installing

=== Prepare the account

You don't need a service account. The integrated IIS application pool identity is sufficient if you use HTTP basic authentication.

=== Install IIS

Install IIS with the following basic feature set.

....
Add-WindowsFeature -Name Web-Server,Web-Asp-Net45,Web-Basic-Auth -IncludeManagementTools
....

Ensure you have a SSL certificate installed and require SSL on the web site you plan to install the API onto.

=== Install AdcsToRest

Simply copy the files into the designated Web Root. No application configuration required.

=== Configure IIS

Configure your SSL Binding and ensure the "Require SSL" configuration parameter is set.

For Basic Authentication, on the web site, in authentication settings, do the following:

* Disable anonymous Authentication
* Enable Basic Authentication
* Configure your Default Domain for Basic Authentication

== Using the API

The API currently supports three operations (all similar to the DCOM link:https://docs.microsoft.com/en-us/windows/win32/api/certcli/nn-certcli-icertrequest[ICertRequest^] Interface):

* link:https://docs.microsoft.com/en-us/windows/win32/api/certcli/nf-certcli-icertrequest-submit[Submit^]
* link:https://docs.microsoft.com/en-us/windows/win32/api/certcli/nf-certcli-icertrequest-retrievepending[RetrievePending^]
* link:https://docs.microsoft.com/en-us/windows/win32/api/certcli/nf-certcli-icertrequest-getcacertificate[GetCACertificate^]

The API incorporates Swagger for automated documentation of the API operations. You can reach it under the /swagger directory, which is the default directory when youn access it via browser.

== Troubleshooting

For simplicity, the API does not log to the Windows Event Log. Errors that may occur are forwarded to the client.